In [17]:
import numpy as np
import pandas as pd

In [18]:
train = pd.read_csv('train_updated.csv')
test = pd.read_csv('test_updated.csv')

In [19]:
B1_cols = [col for col in list(train.columns) if col.startswith('B1')]
B2_cols = [col for col in list(train.columns) if col.startswith('B2')]

In [20]:
B1_cols

['B1_P00',
 'B1_P1',
 'B1_P10',
 'B1_P11',
 'B1_P12',
 'B1_P13',
 'B1_P14',
 'B1_P15',
 'B1_P16',
 'B1_P17',
 'B1_P18',
 'B1_P19',
 'B1_P2',
 'B1_P20',
 'B1_P21',
 'B1_P3',
 'B1_P4',
 'B1_P5',
 'B1_P6',
 'B1_P7',
 'B1_P8',
 'B1_P9']

In [21]:
B2_cols

['B2_P00',
 'B2_P1',
 'B2_P10',
 'B2_P11',
 'B2_P12',
 'B2_P13',
 'B2_P14',
 'B2_P15',
 'B2_P16',
 'B2_P17',
 'B2_P18',
 'B2_P2',
 'B2_P20',
 'B2_P3',
 'B2_P4',
 'B2_P5',
 'B2_P6',
 'B2_P7',
 'B2_P8',
 'B2_P9']

In [22]:
from sklearn.model_selection import train_test_split

target_cols = B2_cols
X = train.drop(columns = target_cols)
y = train[target_cols]

In [23]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.25, random_state=10)

In [24]:
X_train

,Gender,Age,Vintage,Is_Active,City_Category,Customer_Category,B1_P00,B1_P1,B1_P10,B1_P11,...,B1_P2,B1_P20,B1_P21,B1_P3,B1_P4,B1_P5,B1_P6,B1_P7,B1_P8,B1_P9
7323,1,-0.347905,0.626868,1,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22247,0,-0.940692,-0.738681,0,1,2,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
11187,1,-1.138288,-0.836221,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11433,0,0.640074,3.845664,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15776,1,-0.545500,0.821947,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10201,1,0.442478,0.334251,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9372,0,0.244882,1.992418,0,1,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28017,0,-1.237085,-0.055907,0,1,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
29199,0,-1.039490,0.431790,1,1,2,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
17673,0,-1.039490,-0.250985,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputClassifier

regr_multirf = MultiOutputClassifier(RandomForestClassifier())
regr_multirf.fit(X_train, y_train)

regr_rf = RandomForestClassifier()
regr_rf.fit(X_train, y_train)

RandomForestClassifier()

In [27]:
y_multirf = regr_multirf.predict(X_test)
y_rf = regr_rf.predict(X_test)

In [28]:
print(classifier.score(X_test, y_test))

0.18109568718872524